### ISSUE TITLE
Never stops running

### ISSUE THREAD

**Issue by kevmodrome** [rspieker/jest-transform-svelte#12] opened 2019-11-14 12:17 UTC
I've been having some issues getting this to work with Sapper.

Everything works fine as long as I don't add a preprocessor but as soon as I add one it gets stuck in an infinite loop. These are my config files:

jest.config.js:
```javascript
const sveltePreprocess = require('svelte-preprocess')

module.exports = {
	transform: {
		'^.+\\.svelte$': ['jest-transform-svelte', { preprocess: sveltePreprocess() }],
		'^.+\\.js$': 'babel-jest',
	},
	"setupFilesAfterEnv": ["@testing-library/jest-dom/extend-expect"]
};
```

babel.config.js:
```javascript
module.exports = {
	presets: ["@babel/preset-env"],
	plugins: [
		"@babel/plugin-syntax-dynamic-import",
		[
			"@babel/plugin-transform-runtime",
			{
				useESModules: true
			}
		]
	]
};

```

And the test is simply:
```javascript
import "@testing-library/jest-dom/extend-expect";
import { render } from "@testing-library/svelte";
import Button from "./Button.svelte";

test("shows proper heading when rendered", () => {
	const { getByText } = render(Button);

	expect(getByText("Default")).toBeInTheDocument();
});
```

Not sure if it's an issue with this package or if it's another package that is not doing it's thing. Trying the same thing with svelte-test/transform results in a similar result but instead of running forever it spits out an empty div. I've tried with both svelte-preprocessor as well as svelte-preprocessor-sass. Same issue with both.

**Comment by sindreij** [comment] 2019-12-03 14:35
We have the same problem. Adding a preprocessor makes the tests hang forever. Have you found any solutions?

**Comment by kevmodrome** [comment] 2019-12-03 14:48
No solution yet, unfortunately

**Comment by mihar-22** [comment] 2019-12-04 07:26
I can't seem to isolate the bug but it has to either do with `deasync` or node itself. The problem is that a Jest transformer runs synchronously and so `async` code doesn't work. `svelte.preprocess` runs asynchronously and `deasync` was used to wait for the result. I've tried other ways of waiting for the result but nothing works. If you remove `deasync` and log inside the preprocess promise it returns the result, but of course it's returned too late.

**Comment by andrey-ponamarev** [comment] 2020-01-15 12:13
The issue comes from `deasync` version 0.1.15 it is not supporting the latest node version (^12).
`deasync` v0.1.19 has bug fix for it.
While [PR](https://github.com/rspieker/jest-transform-svelte/pull/15) is not merged the easiest way to solve problem in your project is install the latest `deasync` as dependency

**Comment by rspieker** [comment] 2020-01-16 06:57
With the merge of #15 this should be fixed

**Closed by rspieker** 2020-01-16 06:57 UTC

**Comment by beomy** [comment] 2020-05-26 05:36
I still has this problem. My Node.js version is 12.16.3

**Comment by morriq** [comment] 2020-07-08 10:49
could we reopen it? we still have this issue
